core/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html'), name='login'),
    path('', include('administraction.urls')),
    path('', include('books.urls')),
    path('', include('loadns.urls')),
    path('', include('dashboard.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', lambda request: redirect('index', permanent=True)),
]

from django.conf.urls import handler403, handler404, handler500

# Registrar las páginas de error
handler403 = 'dashboard.views.error_403'
handler404 = 'dashboard.views.error_404'
handler500 = 'dashboard.views.error_500'

loadns/urls.py
from django.urls import path, include
from . import views


loan_patterns = [
    path('', views.loan_main, name='loan.index'),
    path('create/', views.loan_create, name='loan.create'),
    path('<int:id>/show/', views.loan_show, name='loan.show'),
    path('<int:id>/edit/', views.loan_update, name='loan.update'),
    path('<int:id>/delete/', views.loan_delete, name='loan.delete'),
    path('<int:id>/return/', views.loan_return, name='loan.return'),
    
]

urlpatterns = [
    path('prestamos/', include(loan_patterns)),
]

loadns/models.py
from django.db import models
from administraction.models import Student, Sanction
from books.models import Copy
from django.contrib.auth.models import User
from utils.utils import generate_qr, generate_code
from utils.utils import  delete_img
from datetime import date
from django.core.exceptions import ValidationError
from cloudinary.models import CloudinaryField
# Create your models here.

class Loan(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    code = models.CharField(max_length=12, unique=True, null=True)
    qr_code = CloudinaryField('photo', transformation={'quality': 'auto:eco'} , folder="Loans_Qrs" )
    copy = models.ForeignKey(Copy, on_delete=models.CASCADE)
    created_by_admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name='loans_created')
    received_by_admin = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='loans_received')
    sanctions = models.ManyToManyField(Sanction, blank=True)
    comment = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField()
    return_date = models.DateTimeField(null=True)
    

    def __str__(self):
        return f"Loan {self.code} - {self.student}"
    
    @property
    def is_returned(self):
        return self.return_date is not None
    
    @property
    def is_active(self):
        return not self.is_returned
    
    @property
    def is_late(self):
        return date.today() < self.due_date
    
    @property
    def is_pending(self):
        return self.is_active and not self.is_late   
    
    @property
    def is_late_return(self):
        return self.is_returned and self.return_date.date() > self.due_date
    
    def delete(self,*args, **kwargs):
        if self.qr_code:
            delete_img(self.qr_code)
        super().delete(*args, **kwargs)

    def clean(self):
        if not self.due_date:
            raise ValidationError('Ingresar fecha de devolucion')  
        if self.due_date < date.today() and not self.pk:
            raise ValidationError('La fecha de devolución no puede ser menor a la fecha actual')       
    
    def save(self, *args, **kwargs):
        if not self.pk:  # Only when creating a new instance
            self.copy.availability_status = False
            self.copy.save()
            self.code = generate_code(length=12)
            self.qr_code = generate_qr(self.code)
        super().save(*args, **kwargs)

loadns/forms.py
from django import forms
from .models import Loan
from datetime import datetime, timedelta
from books.models import Copy

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['student', 'copy', 'comment', 'due_date']
        labels = {
            'student': 'Estudiante',
            'copy': 'Copia',
            'comment': 'Comentario',
            'due_date': 'Fecha Limite de devolucion',
        }
        widgets = {
            'student': forms.Select(attrs={
                'class': 'form-control'
            }),
            'copy': forms.Select(attrs={
                'class': 'form-control'
            }),
            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Escribe un comentario',
                'rows': 3,
            }),
            'due_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',
                'placeholder': 'Fecha que se tiene que devolver',
                'min': (datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d'),
                'value': (datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d'),
            }),
            
        }
        error_messages = {
            'due_date': {
                'invalid': "Introduce una fecha válida.",
                'required': "Este campo es obligatorio.",
            }
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        available_copies = Copy.objects.filter(availability_status=True)
        if not available_copies.exists():
            self.fields['copy'].choices = [('', 'No hay copias disponibles')]
        else:
            self.fields['copy'].queryset = available_copies
        # add a condition to filter sanctioned students
            
    def clean_due_date(self):
        due_date = self.cleaned_data.get('due_date')
        if due_date < datetime.now().date() + timedelta(days=1):
            raise forms.ValidationError("La fecha de devolución no puede ser anterior a mañana.")
        return due_date


class LoanUpdateForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['comment', 'sanctions', 'due_date', 'code']
        labels = {
            'comment': 'Comentario',
            'sanctions': 'Sanciones',
          
            'due_date': 'Fecha Limite de devolucion',
            'code': 'Código',
        }
        widgets = {
            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Escribe un comentario',
                'rows': 3,
            }),
            'sanctions': forms.SelectMultiple(attrs={
                'class': 'form-control',
            }),
            'due_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',
                'readonly': True,
            }),
            'code': forms.TextInput(attrs={
                'class': 'form-control',
                'readonly': True,
            }),
        }


class LoanReturnForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['comment', 'sanctions']
        labels = {
            'comment': 'Comentario',
            'sanctions': 'Sanciones',
        }
        widgets = {
            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Escribe un comentario',
                'rows': 3,
            }),
            'sanctions': forms.SelectMultiple(attrs={
                'class': 'form-control',
            }),
        }

loadns/views.py
from datetime import datetime
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, redirect, get_object_or_404
from administraction.models import Student, Author, Sanction
from .models import Loan
from .forms import LoanForm, LoanUpdateForm, LoanReturnForm
from django.contrib import messages
from utils.utils import admin_required
from django.utils import timezone
from django.contrib.auth.models import User

# Create your views here.


@admin_required
def loan_main(request):
    """
    Handle the main loan view.
    This view handles GET requests to display a list of loans. It prepares
    the context with loan data and renders the 'home/Loan/main.html' template.
    Args:
        request (HttpRequest): The HTTP request object.
    Returns:
        HttpResponse: The rendered HTML page with the context data.
    """
    
    if request.method != 'GET':
        return HttpResponseNotAllowed(['GET'])
        
    
    loans = Loan.objects.all()
    
    table = {
        'title' : 'Tabla Prestamos',
        'headers': ['Codigo de Prestamo', 'Copia','Empretador?', 'Fecha de Prestamos', 'Fecha Limite' ],
        'fields': ['code', 'copy','student','created_date', 'due_date'],
        'data' : loans,
        'accions':{
            'show': 'loan.show',
            'delete': 'loan.delete',
            'return': 'loan.return'
        },
       
    }
    
    context = {
        'table': table,
        'form': LoanForm(),
        'form_return': LoanReturnForm(),
        'today': datetime.now()
    }
        
    return render(request, 'home/Loan/main.html', context)        


@admin_required
def loan_create(request):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    
    form = LoanForm(request.POST, request.FILES)
    
    if not form.is_valid():
        messages.error(request, f"Error en el formulario: {form.errors}")
        return redirect(request.META.get('HTTP_REFERER', 'loan.index'))    

    if not form.cleaned_data['copy'].availability_status:
        messages.error(request, f"Error en el formulario: La copia no esta disponible") 
        return redirect(request.META.get('HTTP_REFERER', 'loan.index'))    
        
    loan = form.save(commit=False)
    loan.created_by_admin = request.user
    loan.save()
    messages.success(request, "Préstamo creado exitosamente")
        
    return redirect(request.META.get('HTTP_REFERER', 'loan.index'))
    
    
    
def process_loan_return(loan, user):
    loan.return_date = timezone.now()
    loan.received_by_admin = user
    
    if loan.return_date.date() > loan.due_date:
        sanction, _ = Sanction.objects.get_or_create(name='Tardanza')
        loan.sanctions.add(sanction)

def update_copy_status(copy):
    copy.availability_status = True
    copy.save()



@admin_required
def loan_return(request, id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    loan = get_object_or_404(Loan, id=id)
    
    if loan.return_date:
        messages.error(request, "El préstamo ya ha sido devuelto anteriormente.")
        return redirect(request.META.get('HTTP_REFERER', 'loan.index'))
    
    process_loan_return(loan, request.user)
    
    form = LoanReturnForm(request.POST, instance=loan)
    
    if not form.is_valid():
        messages.error(request, f"Error en el formulario: {form.errors}")
        return redirect(request.META.get('HTTP_REFERER', 'loan.index'))    
    copy =  loan.copy
    update_copy_status(copy)
    
    form.save()
    
    messages.success(request, "Préstamo devuelto exitosamente")
    
    return redirect(request.META.get('HTTP_REFERER', 'loan.index'))
    


@admin_required
def loan_delete(request, id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    
    loan = get_object_or_404(Loan, id=id)
    
    if loan.return_date:
        messages.danger(request, "No se puede eliminar un préstamo que ya se ha devuelto")
        return redirect(request.META.get('HTTP_REFERER', 'loan.index'))
    
    copy = loan.copy
    copy.availability_status = True
    copy.save()
    loan.delete()
    messages.info(request, "Préstamo eliminado exitosamente")
    return redirect(request.META.get('HTTP_REFERER', 'loan.index'))


@admin_required
def loan_show(request, id):
    if request.method != 'GET':
        return HttpResponseNotAllowed(['GET'])

    loan = get_object_or_404(Loan, id=id)
    form = LoanUpdateForm(instance=loan)  
    context = {
        'loan': loan,
        'form': form,
        'today': datetime.now(),
        'form_return': LoanReturnForm(),
    }
    return render(request, 'home/Loan/show.html', context)   
    

@admin_required    
def loan_update(request, id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    loan = get_object_or_404(Loan, id=id)
    form = LoanUpdateForm(request.POST, request.FILES, instance=loan)
    if form.is_valid():
        form.save()
        messages.success(request, "Préstamo actualizado exitosamente")
        
    else:
        messages.error(request, f"Error al actualizar el préstamo: {form.errors}")
    return redirect('loan.show', id=id)
   

loadns/templates/components/card_copy_loan.html
 {% load static %}

 <div class="card ">
        <a href="{% url 'book.show' book.id%}" target="_blank">
            <img src="{{ book.photo.url }}" alt="Image placeholder" class="card-img-top" style="max-height: 250px; object-fit: cover;" >
        </a>
       
        
        <div class="card-body ">
          
          <div class="text-center mt-3 mb-0 pb-0">
            <a class="h2"  href="{% url 'book.show' book.id %}" target="_blank">
              {{ book.title|title }}
            </a>
            <br>
            <a class="h4 text-muted pb-3 mt-0" href="{% url 'author.show' book.author.id %}" target="_blank">
              {{ book.author.first_name|title }} {{ book.author.last_name|title }}
            </a>
             <br>
            <a class="h5 text-muted pb-3 mt-0"  href="{% url 'copy.show' copy.id %}" target="_blank">
              {{ copy.code_internal }}
            </a>
          </div>

        </div>

      </div>

loadns/templates/components/card_profile_loan.html
 {% load static %}

 <div class="card card-profile">
        
        <img src="/static/assets/img/theme/img-1-1000x600.jpg" alt="Image placeholder" class="card-img-top" style="max-height: 150px; object-fit: cover;">

        <div class="row justify-content-center ">
          <div class="col-lg-3 order-lg-2">
            <div class="card-profile-image w-100 mb-3">
              <a href="{% url 'user.show' user.id%}" target="_blank">
                <img src="{{ user.photo.url }} " class="rounded-circle" >
              </a>
            </div>

          </div>
        </div>

        <div class="card-body mt-5 pt-4 ">
          
          <div class="text-center mt-3 mb-0 pb-0">
            <a class="h2" href="{% url 'user.show' user.id%}" target="_blank">
              {{ user.first_name|title }} {{ user.last_name|title }}
            </a>
            <h5 class="h4 text-muted  pb-3 mt-0">
              {{ user.code_student }}
            </h5>
          </div>

        </div>

      </div>

loadns/templates/components/data_table_loan.html
{% load custom_tags %}
<table id="{{table_id}}" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                {% for header in headers  %}
                    <th>{{header}}</th>
                {% endfor %}
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for item in data  %}
             <tr>
                {% for field in fields  %}
                    {% if field == 'due_date' %}
                        <td>{{ item|get_item:field|date:"Y-m-d" }}</td>
                    {% elif field == 'created_date' %}
                        <td>{{ item|get_item:field|date:"Y-m-d H:i:s" }}</td>
                    {% else %}
                        <td>{{ item|get_item:field }}</td>
                    {% endif %}
                    
                {% endfor %}
                <td>
                     
                    {% if not item.is_returned %}
                        {% if  item.is_pending %}
                            <span class="badge bg-yellow text-dark font-weight-bold"> <b> Atrasado </b></span>
                        {% else %}
                            <span class="badge bg-primary text-white font-weight-bold"> <b> Activo </b></span>
                        {% endif %}
                    {% else %}
                        {% if item.is_late_return %}
                            <span class="badge bg-danger text-white font-weight-bold"> <b> Devuelto tarde </b></span>
                        {% else %}
                            <span class="badge bg-success text-dark font-weight-bold"> <b> Devuelto </b></span>
                        {% endif %}
                        
                    {% endif %}
                    
                </td>

                <td>
                    
                    {% if accions.show %}
                    <a data-bs-toggle="modal" data-bs-target="#showData-1" title="Ver detalles"  class="btn btn-default btn-sm p-0 px-3 py-2 " href="{%url accions.show item.id %}"><i class="fas fa-eye"></i></a>
                    {% endif %}

                    {% if accions.return %}
                    <button class="btn btn-success return-button btn-sm p-0 px-3 py-2" title="Retornar Prestamo" data-loan-code="{{ item.code }}" data-loan-student="{{ item.student }}" data-loan-copy="{{ item.copy }}" data-loan-created-date="{{item.created_date|date:"Y-m-d"}}" data-loan-due-date="{{ item.due_date|date:"Y-m-d" }}" data-return-url="{% url accions.return item.id %}" {%if item.return_date %} disabled   {% endif %}><i class="fas fa-undo" ></i></button>
                    {% endif %}

                    {% if accions.update %}
                    <a data-bs-toggle="modal" data-bs-target="#EditData-1" title="Actualizar" class="btn btn-primary btn-sm p-0 px-3 py-2 " href="{%url accions.update item.id %}"><i class="fas fa-edit"></i></a>
                    {% endif %}

                    {% if accions.delete %}
                    <button class="btn btn-danger delete-button btn-sm p-0 px-3 py-2 "  title="Eliminar" data-delete-url="{% url accions.delete item.id %}" type="button" ><i class="fas fa-trash-alt"></i></button>
                    {% endif %}
                                       
                   
                </td>
            </tr>
            {% endfor %}
            
            
        </tbody>
        <tfoot>
            <tr>
              
                {% for header in headers  %}
                    <th>{{header}}</th>
                {% endfor %}
                <th>Accions</th>
                
            </tr>
        </tfoot>
    </table>

    
{% include 'components/modal_delete.html' with title_modal='Confirmar Eliminación' modal_id='deleteModal' %}
  
{% if accions.return %}
    {% include 'components/modal_return.html' with title_modal='Retornar Libro' modal_id='returnModal' form=form_return %}
{% endif %}

loadns/templates/components/form_update_loan.html
{% extends "components/form_card.html" %}

{% block form_data %} action="{% url 'loan.update' loan.id %}" method="POST" {% endblock form_data %}

{% block body %}
  <h6 class="heading-small text-muted mb-4">Información del préstamo</h6>
  <div class="pl-lg-4">

    <div class="row">
      <div class="col-lg-6">
        {% include "components/input_form.html" with form=form.code class="" %}
      </div>

      <div class="col-lg-6">
        <div class="form-group">                    
          <label class="form-control-label" for="id_created_date">Fecha y hora de creación</label>
          <input type="datetime-local" name="created_date" value="{{ loan.created_date|date:'Y-m-d\\TH:i' }}" class="form-control" readonly="" required="" disabled="true" id="id_created_date">
        </div>
      </div>

    </div>


   <div class="row">
      <div class="col-lg-6">
        <div class="form-group">                    
          <label class="form-control-label" for="id_copy">Copia</label>
          <select name="copy" class="form-control" readonly="" id="id_copy" disabled="true">
            <option value="3" selected="">programacion basica xdxxd -- 1231231231</option>
          </select>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group">                    
          <label class="form-control-label" for="id_student">Estudiante</label>
          <select name="student" class="form-control" readonly="" id="id_student" disabled="true">
            <option value="1" selected="">yerson sanchez</option>
          </select>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        {% include "components/input_form.html" with form=form.due_date class="" %}
      </div>
      <div class="col-lg-6">
        <div class="form-group">                    
          <label class="form-control-label" for="id_return_date">Fecha de devolución</label>
          <input type="date" name="return_date" class="form-control" readonly="" disabled="true" id="id_return_date">
      </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">                    
            <label class="form-control-label" for="id_created_by_admin">Admin que creo</label>
            <select name="created_by_admin" class="form-control" readonly="" id="id_created_by_admin" disabled="" >
              <option value="1" selected="">{{loan.created_by_admin}}</option>
            </select>
        </div>
      </div>

      <div class="col-lg-6">
       <div class="form-group">                    
          <label class="form-control-label" for="id_received_by_admin">Admin que recibio</label>
          <select name="received_by_admin" class="form-control" readonly="" disabled="" required="" id="id_received_by_admin">
            <option value="" selected="">No hay admin receptor</option>
          </select>
      </div>
      </div>
    </div>


    <div class="row">
      <div class="col-lg-12">
        {% include "components/input_form.html" with form=form.sanctions class="" %}
      </div>
      <div class="col-lg-12">
        {% include "components/input_form.html" with form=form.comment class="" %}
      </div>
    </div>
  </div>

  <hr class="my-4" />

  <div class="col-4 ml-auto text-right">
    <button type="submit" class="btn btn-primary mx-0">
      <i class="fas fa-edit"></i>
      Actualizar
    </button>
  </div>
{% endblock body %}

loadns/templates/components/input_form.html
<div class="form-group {{class}}">                    
    <label class="form-control-label" for="{{ form.id_for_label }}">{{ form.label }}</label>
    {{ form }}
</div>

loadns/templates/components/modal_create_copy.html
{% extends "components/modal.html" %}
{% block modal_body %}
<form method="POST" action="{% url 'copy.create' %}" role="form" class="form text-left row" > 
    {% csrf_token %}

    <div class="form-group mb-5 col-12"> 
        <label class="form-label" for="{{ form.book.id_for_label }}">{{ form.book.label }}</label>
        <div class="input-group input-group-alternative">
             
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="ni ni-email-83"></i></span>               
            </div>
             {{ form.book }}
        </div>      
    </div>



    <div class="form-group mb-5 col-12"> 
        <label class="form-label" for="{{ form.code_internal.id_for_label }}">{{ form.code_internal.label }}</label>
        <div class="input-group input-group-alternative">
             
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="ni ni-email-83"></i></span>               
            </div>
             {{ form.code_internal }}
        </div>      
    </div>

    <div class="form-group mb-5 col-12"> 
        <label class="form-label" for="{{ form.comment.id_for_label }}">{{ form.comment.label }}</label>
        <div class="input-group input-group-alternative">
             
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="ni ni-email-83"></i></span>               
            </div>
             {{ form.comment }}
        </div>      
    </div>


    <div class="form-group mb-5 col-12"> 
        <label class="form-label" for="{{ form.location.id_for_label }}">{{ form.location.label }}</label>
        <div class="input-group input-group-alternative">
             
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="ni ni-email-83"></i></span>               
            </div>
             {{ form.location }}
        </div>      
    </div>


    <div class="form-group mb-3 col-12 col-md-3 ml-auto"> 
       
        <button type="submit" class="btn btn-primary mt-3 col-12">Registrar</button>
    </div>
</form>
{% endblock %}

loadns/templates/components/modal_create_loan.html
{% extends "components/modal.html" %}
{% block modal_body %}
<form method="POST" action="{% url 'loan.create' %}" role="form" class="form text-left row"> 
    {% csrf_token %}

    <div class="form-group mb-5 col-12"> 
        <label class="form-label" for="{{ form.student.id_for_label }}">{{ form.student.label }}</label>
        <div class="input-group input-group-alternative">
             
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="ni ni-email-83"></i></span>               
            </div>
             {{ form.student }}
        </div>      
    </div>



    <div class="form-group mb-5 col-12"> 
        <label class="form-label" for="{{ form.copy.id_for_label }}">{{ form.copy.label }}</label>
        <div class="input-group input-group-alternative">
             
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="ni ni-email-83"></i></span>               
            </div>
             {{ form.copy }}
        </div>      
    </div>


    <div class="form-group mb-5 col-12"> 
        <label class="form-label" for="{{ form.comment.id_for_label }}">{{ form.comment.label }}</label>
        <div class="input-group input-group-alternative">
             
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="ni ni-email-83"></i></span>               
            </div>
             {{ form.comment }}
        </div>      
    </div>

    <div class="form-group mb-5 col-12"> 
        <label class="form-label" for="{{ form.due_date.id_for_label }}">{{ form.due_date.label }}</label>
        <div class="input-group input-group-alternative">
             
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="ni ni-email-83"></i></span>               
            </div>
             {{ form.due_date }}
        </div>      
    </div>


    <div class="form-group mb-3 col-12 col-md-3 ml-auto"> 
       
        <button type="submit" class="btn btn-primary mt-3 col-12">Registrar</button>
    </div>
</form>
{% endblock %}